In [1]:
from numpy import *
a = arange(10).reshape(2,5)
print(a)
print(a.shape)
print(a,ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]] <function ndim at 0x0000027651D066A8>
int32
4
10
<class 'numpy.ndarray'>


In [2]:
b = array([6,7,8])
print(b)
print(type(b))

[6 7 8]
<class 'numpy.ndarray'>


In [3]:
from numpy import *
a = array([2,3,4])
print(a)
print(a.dtype)
b = array([1.2, 3.5, 5.1])
print(b.dtype)

[2 3 4]
int32
float64


In [4]:
b = array([(1.5,2,3),(4,5,6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [5]:
c = array([[1,2],[3,4]], dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [6]:
zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:

ones((2,3,4), dtype=int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [8]:
empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
arange(10, 30, 5)

array([10, 15, 20, 25])

In [10]:
arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [11]:
linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
x = linspace(0,2+pi, 100)
print(x)

[0.         0.05193528 0.10387056 0.15580584 0.20774112 0.2596764
 0.31161168 0.36354696 0.41548223 0.46741751 0.51935279 0.57128807
 0.62322335 0.67515863 0.72709391 0.77902919 0.83096447 0.88289975
 0.93483503 0.98677031 1.03870559 1.09064087 1.14257615 1.19451142
 1.2464467  1.29838198 1.35031726 1.40225254 1.45418782 1.5061231
 1.55805838 1.60999366 1.66192894 1.71386422 1.7657995  1.81773478
 1.86967006 1.92160534 1.97354061 2.02547589 2.07741117 2.12934645
 2.18128173 2.23321701 2.28515229 2.33708757 2.38902285 2.44095813
 2.49289341 2.54482869 2.59676397 2.64869925 2.70063453 2.7525698
 2.80450508 2.85644036 2.90837564 2.96031092 3.0122462  3.06418148
 3.11611676 3.16805204 3.21998732 3.2719226  3.32385788 3.37579316
 3.42772844 3.47966372 3.53159899 3.58353427 3.63546955 3.68740483
 3.73934011 3.79127539 3.84321067 3.89514595 3.94708123 3.99901651
 4.05095179 4.10288707 4.15482235 4.20675763 4.2586929  4.31062818
 4.36256346 4.41449874 4.46643402 4.5183693  4.57030458 4.6222398

In [13]:
f = sin(x)
print(f)

[ 0.          0.05191194  0.10368388  0.15517623  0.20625011  0.25676781
  0.30659309  0.35559159  0.40363118  0.45058232  0.49631838  0.54071603
  0.58365555  0.62502115  0.66470128  0.70258893  0.73858192  0.77258321
  0.8045011   0.83424952  0.86174825  0.88692312  0.90970626  0.93003623
  0.9478582   0.96312411  0.97579279  0.98583009  0.99320893  0.99790942
  0.99991887  0.99923188  0.9958503   0.98978323  0.98104706  0.96966532
  0.95566872  0.939095    0.91998885  0.8984018   0.87439206  0.84802437
  0.81936985  0.78850576  0.75551533  0.72048752  0.6835168   0.64470287
  0.60415038  0.56196871  0.51827159  0.47317686  0.42680614  0.37928446
  0.33073997  0.2813036   0.23110863  0.18029045  0.12898608  0.07733388
  0.02547314 -0.0264563  -0.07831439 -0.1299613  -0.18125774 -0.23206539
 -0.28224724 -0.33166796 -0.38019428 -0.42769535 -0.47404306 -0.51911244
 -0.56278194 -0.60493381 -0.64545437 -0.68423436 -0.72116919 -0.75615928
 -0.78911025 -0.81993325 -0.84854517 -0.87486885 -0

In [14]:
a = arange(6)
print(a)

[0 1 2 3 4 5]


In [15]:
b = arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
c = arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [17]:
print(arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [18]:
print(arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [19]:
a = array( [20,30,40,50])
b = arange(4)
print(b)

[0 1 2 3]


In [21]:
c = a-b
print(c)

[20 29 38 47]


In [22]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [23]:
10*sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [24]:
a<35

array([ True,  True, False, False])

In [25]:
A = array([[1,1],[0,1]])
B = array([[2,0],[3,4]])
print(A*B)
print(dot(A,B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [26]:
a = ones((2,3), dtype=int)
b = random.random((2,3))
a *= 3
print(a)

[[3 3 3]
 [3 3 3]]


In [27]:
b += a
print(b)

[[3.11732864 3.41075068 3.88538062]
 [3.85379116 3.26050876 3.01736294]]


In [29]:
a = ones(3, dtype=int32)
b = linspace(0, pi, 3)
print(b.dtype.name)
c = a+b
print(c)
print(c.dtype.name)
d = exp(c*1j)
print(d)
print(d.dtype.name)

float64
[1.         2.57079633 4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [30]:
a = random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.25737101 0.01588045 0.34257013]
 [0.74034743 0.60172112 0.73223838]]
2.6901285130975885
0.015880451503231363
0.7403474266846828


In [31]:
b = arange(12).reshape(3,4)
print(b)
print(b.sum(axis=0))
print(b.min(axis=1))
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [32]:
B = arange(3)
print(B)
print(exp(B))
print(sqrt(B))
C = array([2.,-1.,4.])
print(add(B,C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]
