In [1]:
# 1
import numpy as np

In [6]:
# 2
np.__version__
#np.show_config()

'1.15.4'

In [4]:
# 3
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# 4
print(null_vector.itemsize) # 一要素のバイト数
print(null_vector.size) # 配列の要素数

8
10


In [14]:
# 5
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


In [16]:
# 6
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [24]:
# 7
Z = np.arange(10,50) # arangeは等差や数列を生成する
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [30]:
# 8
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [37]:
# 9
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
# 10
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [43]:
# 11
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# 12
Z = np.random.random((3,3,3))
Z

array([[[0.87657934, 0.04012949, 0.83179077],
        [0.91054489, 0.77131578, 0.33065055],
        [0.38110235, 0.64351589, 0.66221978]],

       [[0.90974652, 0.00990754, 0.31002218],
        [0.45471913, 0.04607618, 0.13383704],
        [0.71407605, 0.62360702, 0.82140099]],

       [[0.15639689, 0.41344551, 0.21411629],
        [0.63657867, 0.59426645, 0.23591692],
        [0.30749411, 0.10990068, 0.44756993]]])

In [46]:
# 13
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print(Zmin, Zmax)

[[8.78588796e-01 4.09590592e-01 9.37633980e-01 8.51255607e-01
  8.34622883e-01 8.18183352e-01 9.62204564e-01 8.66828633e-01
  9.08390764e-01 4.96864548e-01]
 [5.79186941e-01 9.13081583e-01 1.87735908e-01 7.41524940e-01
  3.99795431e-01 8.45870552e-01 9.31510091e-01 4.12157607e-01
  5.07989166e-01 7.29082345e-01]
 [5.73388647e-01 1.90836282e-01 2.81720191e-01 4.78034375e-01
  9.72833999e-02 2.41876219e-01 6.55012695e-01 2.57542571e-01
  8.39354682e-01 2.29349357e-01]
 [8.09409384e-01 6.27262843e-01 6.08932051e-01 7.17600141e-01
  8.77966128e-01 9.84403756e-01 2.72664438e-01 9.41362248e-01
  9.77844039e-01 6.78193429e-01]
 [9.98832399e-01 8.34791365e-01 5.83333882e-01 8.87871608e-01
  4.09960322e-01 3.59358046e-01 6.84969743e-01 1.03572740e-01
  9.85455648e-02 4.48056709e-01]
 [8.30558752e-01 4.38799598e-01 5.68177787e-01 4.91631831e-01
  1.41709131e-01 9.63074680e-01 4.90106383e-01 3.29787413e-01
  7.09676280e-01 7.22550393e-02]
 [4.93721991e-01 2.94630283e-01 6.05532508e-01 1.85495814e

In [47]:
# 14
Z = np.random.random(30)
print(Z)
print(Z.mean())

[0.43674151 0.53770157 0.505413   0.26204175 0.07907502 0.91412791
 0.62691196 0.57244855 0.69505577 0.13205379 0.14834148 0.03654287
 0.29119257 0.79148371 0.24111041 0.99427518 0.16761898 0.06543685
 0.1070924  0.25314655 0.98800358 0.00928911 0.73175135 0.74486347
 0.52341237 0.13960031 0.57445206 0.31914396 0.45412096 0.44867517]
0.4263708051606915


In [51]:
# 15
Z = np.ones((10, 10))
Z[1:-1,1:-1] = 0
Z[2:-2,2:-2] = 1
Z[3:-3,3:-3] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
# 16
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [62]:
# 17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan])) # セットに特定の値が含まれているかを判定
print(3 * 0.1) # 誤差誤差誤差後差誤差誤差

nan
False
False
nan
True
0.30000000000000004


In [73]:
# 18
Z = np.diag(1+np.arange(4), k=-1) 
# kは対角成分の開始位置を示す．
#正の数ならば右横方向へ，負の数ならば下方向へ
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [78]:
# 19
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [79]:
# 20
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [98]:
np.arange(6*7*8).reshape(6,7,8) 

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [97]:
np.unravel_index(99, Z.shape)

(1, 5, 3)