In [1]:
# 1
import numpy as np

In [2]:
# 2
np.__version__
#np.show_config()

'1.16.2'

In [3]:
# 3
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 4
print(null_vector.itemsize) # 一要素のバイト数
print(null_vector.size) # 配列の要素数

8
10


In [5]:
# 5
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


In [6]:
# 6
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# 7
Z = np.arange(10,50) # arangeは等差や数列を生成する
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 8
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
# 9
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 10
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [11]:
# 11
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# 12
Z = np.random.random((3,3,3))
Z

array([[[0.56003259, 0.31497284, 0.67712494],
        [0.16079707, 0.53364469, 0.53967489],
        [0.45072166, 0.04016305, 0.82023568]],

       [[0.74928492, 0.92644567, 0.82816503],
        [0.38427229, 0.66461724, 0.12428903],
        [0.992919  , 0.00773966, 0.27876784]],

       [[0.03004338, 0.12309464, 0.76500374],
        [0.81890204, 0.70081691, 0.81100928],
        [0.83691508, 0.30659161, 0.23366954]]])

In [13]:
# 13
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print(Zmin, Zmax)

[[0.18813364 0.05785611 0.83517015 0.62183484 0.87371428 0.48425563
  0.43349642 0.56629104 0.69574763 0.41683184]
 [0.92464037 0.57740111 0.1686676  0.83382725 0.90319592 0.40561925
  0.33127178 0.5484738  0.20009982 0.66247311]
 [0.58883658 0.55911296 0.78093817 0.79308943 0.80437136 0.73688924
  0.60068223 0.35310644 0.79115264 0.27256901]
 [0.31960558 0.50566476 0.35821039 0.55908528 0.36645255 0.57985354
  0.77100973 0.31825891 0.49642851 0.33331171]
 [0.61311419 0.8700757  0.6987594  0.51149783 0.30864086 0.79370074
  0.98453711 0.9542555  0.5732948  0.0504116 ]
 [0.71964006 0.34412565 0.45105205 0.48402895 0.1279417  0.58031918
  0.70881622 0.51274287 0.65172973 0.77613514]
 [0.60837831 0.5525308  0.46959907 0.68372201 0.32737882 0.454006
  0.87086345 0.6315164  0.42784777 0.4784534 ]
 [0.66307688 0.72610451 0.33410248 0.45280003 0.5327165  0.90612082
  0.28322604 0.5297361  0.5460357  0.81834133]
 [0.34367398 0.60917585 0.11899458 0.78674241 0.64633871 0.18543746
  0.7539749  0

In [14]:
# 14
Z = np.random.random(30)
print(Z)
print(Z.mean())

[0.17110027 0.36685676 0.89102849 0.03216025 0.05153893 0.69868401
 0.69533454 0.68055383 0.34675935 0.63940609 0.67791636 0.82555542
 0.78295563 0.96920291 0.0911463  0.92179976 0.63315786 0.2699363
 0.101496   0.96578644 0.57917442 0.61777269 0.12924347 0.41786503
 0.97122194 0.97185004 0.31217006 0.62825555 0.91437598 0.61245136]
0.5655585348188584


In [15]:
# 15
Z = np.ones((10, 10))
Z[1:-1,1:-1] = 0
Z[2:-2,2:-2] = 1
Z[3:-3,3:-3] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
# 16
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# 17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan])) # セットに特定の値が含まれているかを判定
print(3 * 0.1) # 誤差誤差誤差後差誤差誤差

nan
False
False
nan
True
0.30000000000000004


In [18]:
# 18
Z = np.diag(1+np.arange(4), k=-1) 
# kは対角成分の開始位置を示す．
#正の数ならば右横方向へ，負の数ならば下方向へ
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [19]:
# 19
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [20]:
# 20
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [21]:
np.arange(6*7*8).reshape(6,7,8) 

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [22]:
#21
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#22
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

[[ 1.06410112 -0.93272154 -0.56988697 -1.04952629 -0.72363873]
 [ 0.43923251 -0.7770976   1.45821173  0.19376289 -0.01794778]
 [-0.19898224 -0.78027533 -1.47542979 -0.99546626  1.64353025]
 [ 0.1167553   1.18224667 -1.22311108  1.00699533  1.72535414]
 [-1.13121711  0.81619945 -0.33389473 -0.82660284  1.38940889]]


In [24]:
#23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [25]:
# 24
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [26]:
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [27]:
# 25
Z = np.arange(11)
Z[(3<Z) & (Z<=8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [28]:
# 26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [30]:
# 27
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

In [32]:
# 28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [34]:
# 29
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[-8.  4. -6. -9.  8. -5.  8.  7.  4. -4.]


In [37]:
# 30
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 3 5 8]


In [42]:
# 31
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

_ = np.seterr(**defaults)

#An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [43]:
# 32
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [45]:
# 33
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2019-06-27 2019-06-28 2019-06-29


In [46]:
# 34
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [47]:
# 35
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [54]:
# 36
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[3. 4. 5. 0. 1. 9. 2. 5. 1. 8.]
[3. 4. 5. 0. 1. 9. 2. 5. 1. 8.]
[3. 4. 5. 0. 1. 9. 2. 5. 1. 8.]
[3 4 5 0 1 9 2 5 1 8]
[3. 4. 5. 0. 1. 9. 2. 5. 1. 8.]


In [56]:
# 37
Z = np.zeros((5,5))
print(Z)
Z += np.arange(5)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [58]:
# 38
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(), dtype=float, count=1)
print(Z)

[0.]


In [60]:
# 39
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [63]:
# 40
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06149468 0.14373211 0.17397468 0.17952257 0.51316489 0.60284097
 0.70046053 0.78421268 0.84595386 0.87898595]


In [67]:
# 41
Z = np.arange(10)
np.add.reduce(Z)

45

In [75]:
# 42
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

equal = np.allclose(B,B)
print(equal)

False
False
True


In [79]:
# 43
Z = np.zeros(10)
print(Z)
Z.flags.writeable = False
print(Z)
Z[0] = 1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only