In [1]:
# 1
import numpy as np

In [2]:
# 2
np.__version__
#np.show_config()

'1.16.2'

In [3]:
# 3
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 4
print(null_vector.itemsize) # 一要素のバイト数
print(null_vector.size) # 配列の要素数

8
10


In [5]:
# 5
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


In [6]:
# 6
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# 7
Z = np.arange(10,50) # arangeは等差や数列を生成する
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 8
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
# 9
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 10
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [11]:
# 11
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# 12
Z = np.random.random((3,3,3))
Z

array([[[0.51080566, 0.66815351, 0.2975766 ],
        [0.3666396 , 0.92103724, 0.55002947],
        [0.25830239, 0.6828632 , 0.84864811]],

       [[0.5766347 , 0.22668333, 0.97850749],
        [0.65964553, 0.07578446, 0.53727003],
        [0.20355696, 0.92708478, 0.33621093]],

       [[0.39006625, 0.53280223, 0.64479779],
        [0.32749833, 0.10919047, 0.70559567],
        [0.46286583, 0.49337538, 0.00442304]]])

In [13]:
# 13
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print(Zmin, Zmax)

[[0.24084019 0.58787926 0.46458452 0.97877275 0.77719673 0.53924762
  0.02735527 0.89610711 0.49264894 0.31238523]
 [0.63840334 0.8400425  0.99164389 0.84326245 0.49008267 0.79232757
  0.79216942 0.40658301 0.00218732 0.17855947]
 [0.90644595 0.06678682 0.53689767 0.83300874 0.41610497 0.79153744
  0.76942002 0.43412263 0.89082327 0.69523879]
 [0.34576214 0.87472615 0.60058107 0.99114115 0.60612396 0.63182342
  0.33806657 0.59247937 0.07549422 0.42158854]
 [0.25573329 0.40004754 0.88845302 0.49693529 0.43590341 0.3703128
  0.78885087 0.67518886 0.46420876 0.45074572]
 [0.89831497 0.1056784  0.86437665 0.91136436 0.55750293 0.96661531
  0.69032647 0.75682514 0.35678675 0.32776359]
 [0.02629806 0.64454951 0.34729838 0.6925958  0.94227087 0.8004022
  0.2908497  0.64851942 0.58471501 0.57156327]
 [0.33628662 0.42703881 0.88388858 0.83562636 0.20739516 0.1541136
  0.40749038 0.35046628 0.85484442 0.40689415]
 [0.60804529 0.87814591 0.16889819 0.27793412 0.73124616 0.61763518
  0.55662213 0.

In [14]:
# 14
Z = np.random.random(30)
print(Z)
print(Z.mean())

[0.10145067 0.86737219 0.98836418 0.30407401 0.63330718 0.92299271
 0.99242801 0.50281955 0.55345466 0.30105049 0.8702395  0.61553366
 0.38704987 0.08202805 0.88679923 0.12845104 0.94609738 0.79380271
 0.59120932 0.72701501 0.60246739 0.35771163 0.31310112 0.98677074
 0.05261728 0.76599801 0.64090445 0.57593283 0.26322932 0.74610898]
0.5833460398100979


In [15]:
# 15
Z = np.ones((10, 10))
Z[1:-1,1:-1] = 0
Z[2:-2,2:-2] = 1
Z[3:-3,3:-3] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
# 16
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# 17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan])) # セットに特定の値が含まれているかを判定
print(3 * 0.1) # 誤差誤差誤差後差誤差誤差

nan
False
False
nan
True
0.30000000000000004


In [18]:
# 18
Z = np.diag(1+np.arange(4), k=-1) 
# kは対角成分の開始位置を示す．
#正の数ならば右横方向へ，負の数ならば下方向へ
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [19]:
# 19
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [20]:
# 20
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [21]:
np.arange(6*7*8).reshape(6,7,8) 

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [23]:
#21
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
#22
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

[[-0.07508879 -1.23335565 -0.10657197  0.62357497 -0.03846474]
 [ 0.07158141 -1.83828038  1.45862345 -1.05003273 -0.57359566]
 [ 1.48398223  1.70606646 -0.65369438  0.43355277 -0.75140255]
 [-0.80449797  0.43438639 -0.25199422 -0.26800974  1.60095447]
 [ 1.4579773   0.39566359 -0.62764735  0.4549774  -1.84870431]]


In [28]:
#23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [29]:
# 24
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [31]:
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [34]:
# 25
Z = np.arange(11)
Z[(3<Z) & (Z<=8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [40]:
# 26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10
