In [1]:
# 1
import numpy as np

In [2]:
# 2
np.__version__
#np.show_config()

'1.15.4'

In [3]:
# 3
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 4
print(null_vector.itemsize) # 一要素のバイト数
print(null_vector.size) # 配列の要素数

8
10


In [5]:
# 5
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


In [6]:
# 6
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# 7
Z = np.arange(10,50) # arangeは等差や数列を生成する
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 8
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
# 9
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 10
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [11]:
# 11
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# 12
Z = np.random.random((3,3,3))
Z

array([[[0.67712959, 0.0709234 , 0.18311606],
        [0.93011537, 0.43698183, 0.61255677],
        [0.78574862, 0.83716843, 0.91812228]],

       [[0.92577062, 0.47299866, 0.95411236],
        [0.1883879 , 0.87238463, 0.72459823],
        [0.83538187, 0.88514257, 0.11586125]],

       [[0.80846325, 0.05051014, 0.88765802],
        [0.74476393, 0.75935174, 0.50475364],
        [0.62340153, 0.99299868, 0.48077413]]])

In [13]:
# 13
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print(Zmin, Zmax)

[[0.84003174 0.92535321 0.69789186 0.51353761 0.66320956 0.95508353
  0.08999717 0.96293526 0.35671759 0.00523749]
 [0.85029626 0.44644052 0.20736145 0.80785571 0.49394172 0.38433777
  0.30941916 0.84328028 0.45328347 0.17165588]
 [0.35133326 0.1849764  0.41430581 0.62030272 0.41527682 0.33063959
  0.33542897 0.86873979 0.78223013 0.4662092 ]
 [0.85506057 0.4173942  0.88999902 0.43517826 0.54591101 0.90536004
  0.25899331 0.21721865 0.75107183 0.14422374]
 [0.84171673 0.18539164 0.56253298 0.39325762 0.87066805 0.0622717
  0.60590744 0.46646069 0.60770345 0.87373513]
 [0.22378534 0.60413893 0.65068755 0.01755488 0.88044606 0.30991315
  0.01487206 0.2885935  0.79082378 0.77886527]
 [0.49473659 0.55636847 0.07258682 0.3014271  0.91491016 0.6273125
  0.65206312 0.14926998 0.28865706 0.26345294]
 [0.9603725  0.21604676 0.85267218 0.6307206  0.79325652 0.48549238
  0.50673339 0.67157448 0.46806957 0.15653402]
 [0.14010481 0.78574345 0.09203144 0.91444576 0.99080941 0.9382642
  0.09977969 0.

In [14]:
# 14
Z = np.random.random(30)
print(Z)
print(Z.mean())

[0.75512144 0.79580924 0.78236235 0.94256259 0.16285087 0.03424148
 0.14983328 0.10252424 0.14316646 0.34286742 0.44323992 0.50936405
 0.42598138 0.87502663 0.86447718 0.70653529 0.17082728 0.89848441
 0.67964522 0.21401855 0.26182457 0.22373952 0.38578344 0.45650957
 0.00339281 0.49724546 0.70326305 0.88328061 0.98241088 0.05788971]
0.4818092967389175


In [15]:
# 15
Z = np.ones((10, 10))
Z[1:-1,1:-1] = 0
Z[2:-2,2:-2] = 1
Z[3:-3,3:-3] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
# 16
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# 17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan])) # セットに特定の値が含まれているかを判定
print(3 * 0.1) # 誤差誤差誤差後差誤差誤差

nan
False
False
nan
True
0.30000000000000004


In [18]:
# 18
Z = np.diag(1+np.arange(4), k=-1) 
# kは対角成分の開始位置を示す．
#正の数ならば右横方向へ，負の数ならば下方向へ
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [19]:
# 19
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [20]:
# 20
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [21]:
np.arange(6*7*8).reshape(6,7,8) 

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [22]:
#21
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#22
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

[[ 0.49514942 -0.47685607  0.50082063 -0.73198392  1.11635145]
 [-0.88561145  0.61462364 -1.08808702  0.63755668 -0.35003961]
 [ 1.12506392 -1.45374885  1.59895263  1.37998355 -1.58785086]
 [-1.03180672  1.10159055 -0.39893723 -0.59557249  0.01082785]
 [ 1.13795314 -1.13850034 -1.34436246 -0.07164633  1.43612986]]


In [24]:
#23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [25]:
# 24
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [26]:
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [27]:
# 25
Z = np.arange(11)
Z[(3<Z) & (Z<=8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [28]:
# 26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [29]:
# 27
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

In [30]:
# 28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [31]:
# 29
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[ -9.  -2.   5. -10.   7.   3.  -9.   6. -10.  -1.]


In [32]:
# 30
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 3 7 8]


In [33]:
# 31
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

_ = np.seterr(**defaults)

#An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [34]:
# 32
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [35]:
# 33
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2019-06-30 2019-07-01 2019-07-02


In [36]:
# 34
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [37]:
# 35
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [38]:
# 36
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[4. 9. 8. 0. 7. 8. 1. 4. 1. 3.]
[4. 9. 8. 0. 7. 8. 1. 4. 1. 3.]
[4. 9. 8. 0. 7. 8. 1. 4. 1. 3.]
[4 9 8 0 7 8 1 4 1 3]
[4. 9. 8. 0. 7. 8. 1. 4. 1. 3.]


In [39]:
# 37
Z = np.zeros((5,5))
print(Z)
Z += np.arange(5)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [40]:
# 38
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(), dtype=float, count=1)
print(Z)

[0.]


In [41]:
# 39
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [42]:
# 40
Z = np.random.random(10)
Z.sort()
print(Z)

[0.17363123 0.30668409 0.3069586  0.57347349 0.61371395 0.62355655
 0.80210473 0.82765251 0.92110735 0.93146395]


In [43]:
# 41
Z = np.arange(10)
np.add.reduce(Z)

45

In [44]:
# 42
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

equal = np.allclose(B,B)
print(equal)

False
False
True


In [45]:
# 43
Z = np.zeros(10)
print(Z)
Z.flags.writeable = False
print(Z)
Z[0] = 1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

In [46]:
# 44
Z = np.random.random((10, 2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.46018105 0.90277979 0.98183018 0.9887437  1.31322373 0.61562082
 0.88148811 1.25279894 1.00516116 0.55732968]
[0.15098044 0.73966098 0.2438891  1.11036183 0.85264228 1.07597786
 1.17197752 0.73419441 0.10551969 0.05772215]


In [47]:
# 45
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.32281662 0.47714182 0.69572518 0.33253352 0.         0.90602365
 0.46639778 0.57148737 0.287002   0.48036443]


In [50]:
# 46
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [51]:
# 47
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [52]:
X 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [54]:
Y = X +0.5
Y

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5])

In [55]:
np.subtract.outer(X, Y)

array([[-0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5, -7.5],
       [ 0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5],
       [ 1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5],
       [ 2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5],
       [ 3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5],
       [ 4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5],
       [ 5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5],
       [ 6.5,  5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5]])

In [56]:
C = 1.0/ np.subtract.outer(X, Y)
C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

In [57]:
# 48
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float32]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-3.4028235e+38
3.4028235e+38
1.1920929e-07


In [58]:
# 49
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [59]:
# 50
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

58


In [65]:
# 51
Z = np.zeros(10, [ ('position',[('x', float, 1),
                                ('y', float, 1)]),
                   ('color',   [('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [66]:
# 52
Z = np.random.random((10,2))
X, Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.47457571 0.61502898 0.50916927 0.44162752 0.57326933
  0.14538192 0.37305625 0.12528703 0.65373279]
 [0.47457571 0.         0.14465284 0.08034874 0.51331097 0.59352477
  0.34456082 0.47945555 0.59660694 0.6982609 ]
 [0.61502898 0.14465284 0.         0.11573171 0.63466363 0.63581184
  0.48854486 0.56239678 0.73498934 0.7366032 ]
 [0.50916927 0.08034874 0.11573171 0.         0.59100536 0.54238747
  0.39143051 0.45163184 0.62629648 0.64581675]
 [0.44162752 0.51331097 0.63466363 0.59100536 0.         0.94323586
  0.3556539  0.75503094 0.52613288 1.03980453]
 [0.57326933 0.59352477 0.63581184 0.54238747 0.94323586 0.
  0.59286819 0.2002681  0.6016141  0.10503593]
 [0.14538192 0.34456082 0.48854486 0.39143051 0.3556539  0.59286819
  0.         0.40040548 0.27007237 0.68657195]
 [0.37305625 0.47945555 0.56239678 0.45163184 0.75503094 0.2002681
  0.40040548 0.         0.40898085 0.28690714]
 [0.12528703 0.59660694 0.73498934 0.62629648 0.52613288 0.6016141
  0.27007237 0.4089808

In [67]:
# 53
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
# 54
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [69]:
# 55
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [70]:
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
