In [2]:
from numpy import array
a = array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = 2
print(b)

2


In [4]:
c = a + b
print(c)

[3 4 5]


In [5]:
A = array([[1,2,3], [1,2,3]])
print(A)
b = 2
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [6]:
A = array([[1,2,3], [1,2,3]])
print(A)
b = array([1,2,3])
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]
