In [1]:
#from IPython.core.display import display, HTML
#display(HTML('<style>.container{width:100%!important;}</style>'))

In [2]:
import pandas, scipy, numpy
# Setting precision for the output
numpy.set_printoptions(precision=3)

df = pandas.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv',sep=';')
# 行・列のlabel以外を取得
array = df.values
# Separating data into input and output components
x = array[:, 0:8]
y = array[:, 8]

# Scalling Data

In [3]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(x)
print(rescaledX[:5,:])

[[0.248 0.397 0.    0.068 0.107 0.141 0.099 0.568]
 [0.283 0.521 0.    0.116 0.144 0.338 0.216 0.494]
 [0.283 0.438 0.04  0.096 0.134 0.197 0.17  0.509]
 [0.584 0.11  0.56  0.068 0.105 0.225 0.191 0.582]
 [0.248 0.397 0.    0.068 0.107 0.141 0.099 0.568]]


# Standardizing Data

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(x)
rescaledX = scaler.transform(x)
print(rescaledX[0:5,:])

[[-0.528  0.962 -1.391 -0.453 -0.244 -0.466 -0.379  0.558]
 [-0.299  1.967 -1.391  0.043  0.224  0.873  0.624  0.028]
 [-0.299  1.297 -1.186 -0.169  0.096 -0.084  0.229  0.134]
 [ 1.655 -1.384  1.484 -0.453 -0.265  0.108  0.412  0.664]
 [-0.528  0.962 -1.391 -0.453 -0.244 -0.466 -0.379  0.558]]
